# Generated by Django 4.2.16 on 2024-11-06 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstancePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_type', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP')], max_length=10)),
                ('location', models.CharField(db_index=True, max_length=50)),
                ('num_cpu', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ram_gb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instance Price',
                'verbose_name_plural': 'Instance Prices',
                'indexes': [models.Index(fields=['cloud_type', 'location'], name='api_instanc_cloud_t_047898_idx')],
            },
        ),
    ]
